"use client";import{useState}from"react";import{ Briefcase, MapPin, DollarSign, Clock, Search, Filter, Plus }from"lucide-react";
const jobs=[{id:1,title:"Software Engineer",company:"Google",location:"Remote",salary:"₦500,000",type:"Full-time",posted:"2 days ago"},{id:2,title:"Data Analyst",company:"Shell",location:"Lagos",salary:"₦350,000",type:"Contract",posted:"5 days ago"},{id:3,title:"Web Developer",company:"Flutterwave",location:"Remote",salary:"₦400,000",type:"Full-time",posted:"1 week ago"}];
export default function CareerPage(){const[search,setSearch]=useState("");const[tab,setTab]=useState("jobs");
return(<div className="min-h-screen bg-gray-50"><div className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white p-6"><h1 className="text-2xl font-bold">Career Services</h1><p className="text-blue-100">Jobs & placement opportunities</p></div>
<div className="p-4 max-w-7xl mx-auto"><div className="flex gap-2 mb-4">{["jobs","applications","resources"].map(t=>(<button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 rounded-xl font-medium capitalize ${tab===t?"bg-blue-600 text-white":"bg-white text-gray-600"}`}>{t}</button>))}</div>
{tab==="jobs"&&(<><div className="relative mb-4"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/><input type="text"placeholder="Search jobs..."value={search}onChange={e=>setSearch(e.target.value)}className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl"/></div>
<div className="space-y-3">{jobs.map(job=>(<div key={job.id}className="bg-white rounded-xl p-4 border border-gray-100"><div className="flex items-start justify-between"><div><p className="font-semibold text-gray-900">{job.title}</p><p className="text-sm text-gray-500">{job.company}</p></div><span className="px-2 py-1 bg-green-100 text-green-700 text-xs rounded-full">{job.type}</span></div><div className="flex items-center gap-4 mt-3 text-sm text-gray-600"><span className="flex items-center gap-1"><MapPin className="w-4 h-4"/>{job.location}</span><span className="flex items-center gap-1"><DollarSign className="w-4 h-4"/>{job.salary}/mo</span><span className="flex items-center gap-1"><Clock className="w-4 h-4"/>{job.posted}</span></div><button className="mt-3 w-full py-2 bg-blue-600 text-white font-medium rounded-lg">Apply Now</button></div>))}</div></>)}
{tab==="applications"&&(<div className="bg-white rounded-xl p-4 border border-gray-100 text-center"><p className="text-gray-500">No applications yet</p></div>)}
{tab==="resources"&&(<div className="bg-white rounded-xl p-4 border border-gray-100"><h2 className="font-semibold text-gray-900 mb-3">Resources</h2><div className="space-y-2"><p className="p-3 bg-gray-50 rounded-lg">Resume Guide</p><p className="p-3 bg-gray-50 rounded-lg">Interview Tips</p><p className="p-3 bg-gray-50 rounded-lg">Career Fair 2024</p></div></div>)}</div></div>);}
