# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_course_id', models.CharField(max_length=200)),
                ('lms_course_url', models.URLField(blank=True, max_length=500)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('local_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_mappings', to='academic.course')),
            ],
            options={
                'db_table': 'lms_course_mappings',
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_content_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('file', 'File'), ('video', 'Video'), ('link', 'External Link'), ('page', 'Page'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='lms.coursemapping')),
            ],
            options={
                'db_table': 'lms_content_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='lms.coursemapping')),
            ],
            options={
                'db_table': 'lms_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('blackboard', 'Blackboard Learn'), ('canvas', 'Canvas LMS'), ('moodle', 'Moodle')], default='blackboard', max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_instances', to='university.university')),
            ],
            options={
                'db_table': 'lms_instances',
            },
        ),
        migrations.CreateModel(
            name='GradeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_grade_id', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('to_lms', 'To LMS'), ('from_lms', 'From LMS')], default='to_lms', max_length=10)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_syncs', to='academic.enrollment')),
                ('lms_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_syncs', to='lms.lmsinstance')),
            ],
            options={
                'db_table': 'lms_grade_sync',
            },
        ),
        migrations.AddField(
            model_name='coursemapping',
            name='lms_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='lms.lmsinstance'),
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.IntegerField()),
                ('resolutions', models.JSONField(default=list)),
                ('transcript', models.TextField(blank=True)),
                ('subtitles', models.JSONField(default=dict)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_recording', to='lms.contentitem')),
            ],
            options={
                'db_table': 'lms_video_recordings',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_user_id', models.CharField(max_length=200)),
                ('lms_enrollment_id', models.CharField(max_length=200)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_sync', to='academic.enrollment')),
                ('lms_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_syncs', to='lms.lmsinstance')),
            ],
            options={
                'db_table': 'lms_enrollment_sync',
                'unique_together': {('enrollment', 'lms_instance')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursemapping',
            unique_together={('local_course', 'lms_instance')},
        ),
    ]
