# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('CCMAS_compliant', models.BooleanField(default=True)),
                ('dean', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('academic_system', models.CharField(choices=[('british_nigerian', 'British/Nigerian (NUC)'), ('american', 'American (US Style)'), ('polytechnic', 'Nigerian Polytechnic (NBTE)')], default='british_nigerian', max_length=20)),
                ('system_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic')], default='university', max_length=20)),
                ('nuc_accredited', models.BooleanField(default=True)),
                ('nbte_accredited', models.BooleanField(default=False)),
                ('tetfund_qualified', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('sessions_per_year', models.IntegerField(default=2)),
                ('max_courses_per_semester', models.IntegerField(default=6)),
                ('min_courses_per_semester', models.IntegerField(default=4)),
                ('grading_scale', models.CharField(default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('programme_types', models.JSONField(default=list)),
                ('hod', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nuc_accredited', models.BooleanField(default=True)),
                ('accreditation_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.faculty')),
            ],
            options={
                'db_table': 'departments',
                'unique_together': {('faculty', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('programme_type', models.CharField(choices=[('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('doctorate', 'Doctorate (PhD)'), ('nd', 'National Diploma (ND)'), ('hnd', 'Higher National Diploma (HND)'), ('bsc', 'Bachelor of Science'), ('ba', 'Bachelor of Arts'), ('ma', 'Master of Arts'), ('ms', 'Master of Science'), ('phd', 'Doctor of Philosophy')], max_length=20)),
                ('duration_years', models.IntegerField(default=4)),
                ('CCMAS_code', models.CharField(blank=True, max_length=20)),
                ('BMAS_code', models.CharField(blank=True, max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100)),
                ('liberal_arts', models.BooleanField(default=False)),
                ('required_credits', models.IntegerField(blank=True, null=True)),
                ('general_education_credits', models.IntegerField(blank=True, null=True)),
                ('UTME_subjects', models.JSONField(default=list)),
                ('direct_entry_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='university.department')),
            ],
            options={
                'db_table': 'programmes',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='university.university')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-session'],
                'unique_together': {('university', 'session')},
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='university.university'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_start', models.DateField(blank=True, null=True)),
                ('exam_end', models.DateField(blank=True, null=True)),
                ('results_released', models.BooleanField(default=False)),
                ('results_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='university.session')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['semester'],
                'unique_together': {('session', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'code')},
        ),
    ]
