# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPSDataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_date', models.DateField()),
                ('total_records', models.IntegerField(default=0)),
                ('imported_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'caps_data_imports',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='DirectEntryApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('jamb_registration', models.CharField(blank=True, max_length=20)),
                ('jamb_result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('offered', 'Offer Given'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'direct_entry_applications',
            },
        ),
        migrations.CreateModel(
            name='PostUTMEResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField(default=100)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('subject_scores', models.JSONField(default=dict)),
                ('is_passed', models.BooleanField(default=False)),
                ('passing_score', models.IntegerField(default=50)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_utme_results',
            },
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_institution', models.CharField(max_length=200)),
                ('current_programme', models.CharField(max_length=200)),
                ('current_level', models.IntegerField()),
                ('current_cgpa', models.FloatField()),
                ('credits_to_transfer', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('transcript_verified', 'Transcript Verified'), ('screening', 'Screening'), ('offered', 'Offer Given'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transfer_applications',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('jamb_registration_number', models.CharField(max_length=20)),
                ('jamb_score', models.IntegerField()),
                ('jamb_subject_combination', models.JSONField(default=dict)),
                ('caps_application_id', models.CharField(blank=True, max_length=50)),
                ('caps_status', models.CharField(blank=True, max_length=50)),
                ('post_utme_score', models.IntegerField(blank=True, null=True)),
                ('screening_aggregate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('offered', 'Offer Given'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('offer_letter_sent', models.BooleanField(default=False)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('admission_letter_number', models.CharField(blank=True, max_length=30)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_choice_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_applications', to='university.programme')),
                ('offered_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_applications', to='university.programme')),
                ('second_choice_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_applications', to='university.programme')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='university.university')),
            ],
            options={
                'db_table': 'admission_applications',
            },
        ),
        migrations.CreateModel(
            name='AdmissionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('screening_start', models.DateField(blank=True, null=True)),
                ('screening_end', models.DateField(blank=True, null=True)),
                ('jamb_cutoff', models.IntegerField(default=160)),
                ('post_utme_cutoff', models.IntegerField(default=50)),
                ('total_admission_quota', models.IntegerField()),
                ('admitted_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_batches', to='university.university')),
            ],
            options={
                'db_table': 'admission_batches',
            },
        ),
    ]
