# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capsdataimport',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capsdataimport',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caps_imports', to='university.university'),
        ),
        migrations.AddField(
            model_name='directentryapplication',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_applications', to='university.programme'),
        ),
        migrations.AddField(
            model_name='directentryapplication',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_applications', to='university.university'),
        ),
        migrations.AddField(
            model_name='postutmeresult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_utme_results', to='admission.admissionapplication'),
        ),
        migrations.AddField(
            model_name='transferapplication',
            name='target_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_applications', to='university.programme'),
        ),
        migrations.AddField(
            model_name='transferapplication',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_applications', to='university.university'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionapplication',
            unique_together={('university', 'jamb_registration_number')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionbatch',
            unique_together={('university', 'session')},
        ),
    ]
