# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('convocation', 'Convocation'), ('reunion', 'Reunion'), ('networking', 'Networking'), ('donation', 'Donation'), ('meeting', 'General Meeting')], max_length=50)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_events', to='university.university')),
            ],
            options={
                'db_table': 'alumni_events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('convocation_year', models.IntegerField(blank=True, null=True)),
                ('degree_classification', models.CharField(blank=True, max_length=50)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('further_study', 'Further Study'), ('entrepreneur', 'Entrepreneur')], default='employed', max_length=20)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('annual_dues_paid', models.BooleanField(default=False)),
                ('last_dues_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='students.student')),
            ],
            options={
                'db_table': 'alumni_profiles',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('purpose', models.CharField(choices=[('scholarship', 'Scholarship'), ('infrastructure', 'Infrastructure'), ('research', 'Research'), ('general', 'General')], max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='alumni.alumniprofile')),
            ],
            options={
                'db_table': 'alumni_donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='alumni.alumniprofile')),
            ],
            options={
                'db_table': 'alumni_job_placements',
                'ordering': ['-start_date'],
            },
        ),
    ]
