# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_opted_in', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='students.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='university.university')),
            ],
            options={
                'db_table': 'whatsapp_contacts',
                'unique_together': {('university', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('state', models.CharField(default='greeting', max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('message_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='whatsapp.whatsappcontact')),
            ],
            options={
                'db_table': 'chatbot_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('admission', 'Admission'), ('payment', 'Payment'), ('academic', 'Academic'), ('result', 'Result'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('alert', 'Alert')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('header', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('footer', models.CharField(blank=True, max_length=255)),
                ('buttons', models.JSONField(default=list)),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='university.university')),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('sticker', 'Sticker'), ('interactive', 'Interactive'), ('template', 'Template')], max_length=20)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('template_vars', models.JSONField(default=dict)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('wamid', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcontact')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_filter', models.JSONField(default=dict)),
                ('message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='university.university')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'db_table': 'whatsapp_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
