# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='course_materials/')),
                ('file_type', models.CharField(max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_offline_available', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course_materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_points', models.FloatField(blank=True, null=True)),
                ('grading_option', models.CharField(blank=True, max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('drop_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exam_sittings',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_score', models.FloatField(blank=True, help_text='Continuous Assessment', null=True)),
                ('midterm_score', models.FloatField(blank=True, null=True)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('appealed', 'Appealed'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='appeals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appealed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grade_appeals',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField(default=0)),
                ('wing', models.CharField(blank=True, max_length=20)),
                ('warden', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('allocated', 'Allocated')], default='pending', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('bed_number', models.CharField(blank=True, max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hostel_applications',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'timetables',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('venue_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('laboratory', 'Laboratory'), ('exam_hall', 'Exam Hall'), ('auditorium', 'Auditorium')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('exam_capacity', models.IntegerField(default=0)),
                ('can_host_exams', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('units', models.IntegerField(default=3)),
                ('credit_hours', models.IntegerField(default=3)),
                ('course_type', models.CharField(choices=[('core', 'Core/Elective'), ('elective', 'Elective'), ('general', 'General (GEC)'), ('professional', 'Professional'), ('vocational', 'Vocational')], default='core', max_length=20)),
                ('CCMAS_code', models.CharField(blank=True, max_length=20)),
                ('is_industrial_attachment', models.BooleanField(default=False)),
                ('is_project', models.BooleanField(default=False)),
                ('is_long_course', models.BooleanField(default=False)),
                ('prerequisite_courses', models.JSONField(default=list)),
                ('is_general_education', models.BooleanField(default=False)),
                ('distribution_area', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=100)),
                ('semester_offered', models.CharField(blank=True, max_length=20)),
                ('max_capacity', models.IntegerField(default=500)),
                ('current_enrollment', models.IntegerField(default=0)),
                ('ca_weight', models.FloatField(default=30.0)),
                ('exam_weight', models.FloatField(default=70.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.department')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
