# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='academic.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.university'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academic.course'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sittings', to='students.student'),
        ),
        migrations.AddField(
            model_name='examsitting',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sittings', to='academic.course'),
        ),
        migrations.AddField(
            model_name='examsitting',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsitting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sittings', to='university.semester'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.examsitting'),
        ),
        migrations.AddField(
            model_name='grade',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_record', to='academic.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeappeal',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='gradeappeal',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='university.university'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='allocated_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to='academic.hostel'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_apps', to='academic.hostel'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_apps', to='academic.hostel'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='university.semester'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='university.semester'),
        ),
        migrations.AddField(
            model_name='venue',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='university.university'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.venue'),
        ),
        migrations.AddField(
            model_name='examsitting',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sittings', to='academic.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('university', 'code', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam_sitting', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelapplication',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('course', 'semester', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='examsitting',
            unique_together={('course', 'semester', 'date')},
        ),
    ]
