# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('current_menu', models.CharField(max_length=50)),
                ('previous_menu', models.CharField(blank=True, max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='students.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_sessions', to='university.university')),
            ],
            options={
                'db_table': 'ussd_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UssdLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50)),
                ('user_input', models.TextField(blank=True)),
                ('response', models.TextField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ussd.ussdsession')),
            ],
            options={
                'db_table': 'ussd_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UssdMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('entry_point', models.CharField(default='main', max_length=50)),
                ('menu_tree', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_menus', to='university.university')),
            ],
            options={
                'db_table': 'ussd_menus',
                'unique_together': {('university', 'code')},
            },
        ),
    ]
