# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('credential_type', models.CharField(choices=[('certificate', 'Certificate'), ('transcript', 'Transcript'), ('degree', 'Degree'), ('diploma', 'Diploma'), ('badge', 'Digital Badge'), ('certification', 'Professional Certification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('grade_classification', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending Verification')], default='issued', max_length=20)),
                ('verification_hash', models.CharField(max_length=255, unique=True)),
                ('blockchain_txid', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuing_authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credentials', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='university.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='students.student')),
            ],
            options={
                'db_table': 'digital_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('block_timestamp', models.DateTimeField()),
                ('contract_address', models.CharField(max_length=255)),
                ('token_id', models.CharField(blank=True, max_length=255)),
                ('metadata_uri', models.URLField(blank=True, max_length=500)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='credentials.credential')),
            ],
            options={
                'db_table': 'blockchain_records',
            },
        ),
        migrations.CreateModel(
            name='CredentialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_name', models.CharField(max_length=255)),
                ('verifier_email', models.EmailField(blank=True, max_length=254)),
                ('verifier_organization', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='credentials.credential')),
            ],
            options={
                'db_table': 'credential_verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
