"""
Finance Models
Invoices, payments, fees - supports Nigerian payment systems
"""
import uuid
from django.db import models
from django.utils import timezone
from decimal import Decimal


class FeeType(models.Model):
    """Types of fees"""
    
    class FeeCategory(models.TextChoices):
        TUITION = 'tuition', 'Tuition'
        ACADEMIC = 'academic', 'Academic'
        HOSTEL = 'hostel', 'Hostel'
        MEDICAL = 'medical', 'Medical'
        ICT = 'ict', 'ICT'
        LIBRARY = 'library', 'Library'
        REGISTRATION = 'registration', 'Registration'
        OTHER = 'other', 'Other'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    university = models.ForeignKey('university.University', on_delete=models.CASCADE, related_name='fee_types')
    
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=FeeCategory.choices)
    
    # Amount
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    # Applicable levels
    applicable_levels = models.JSONField(default=list)  # List of levels
    
    # System-specific
    is_mandatory = models.BooleanField(default=True)
    is_recurring = models.BooleanField(default=True)
    
    # For Nigerian: TETFund levy
    tetfund_levy = models.BooleanField(default=False)
    tetfund_percentage = models.FloatField(default=0)
    
    is_active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'fee_types'
    
    def __str__(self):
        return f"{self.name} - {self.amount}"


class Invoice(models.Model):
    """Student invoice"""
    
    class InvoiceStatus(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        ISSUED = 'issued', 'Issued'
        PARTIAL = 'partial', 'Partially Paid'
        PAID = 'paid', 'Paid'
        OVERDUE = 'overdue', 'Overdue'
        CANCELLED = 'cancelled', 'Cancelled'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    student = models.ForeignKey('students.Student', on_delete=models.CASCADE, related_name='invoices')
    semester = models.ForeignKey('university.Semester', on_delete=models.CASCADE, related_name='invoices')
    
    invoice_number = models.CharField(max_length=30, unique=True)
    
    # Amounts
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    
    status = models.CharField(max_length=20, choices=InvoiceStatus.choices, default=InvoiceStatus.DRAFT)
    
    # Issue date
    issue_date = models.DateField()
    due_date = models.DateField()
    
    # Discounts/Adjustments
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    adjustment_notes = models.TextField(blank=True)
    
    # Generated by
    generated_by = models.ForeignKey('students.User', on_delete=models.SET_NULL, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'invoices'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.invoice_number} - {self.student.student_id}"
    
    def calculate_balance(self):
        self.balance = self.total_amount - self.paid_amount
        if self.balance <= 0:
            self.status = self.InvoiceStatus.PAID
        elif self.paid_amount > 0:
            self.status = self.InvoiceStatus.PARTIAL
        self.save()


class InvoiceItem(models.Model):
    """Line items on invoice"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
    fee_type = models.ForeignKey(FeeType, on_delete=models.CASCADE)
    
    description = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    class Meta:
        db_table = 'invoice_items'


class Payment(models.Model):
    """Payment records"""
    
    class PaymentStatus(models.TextChoices):
        PENDING = 'pending', 'Pending'
        PROCESSING = 'processing', 'Processing'
        COMPLETED = 'completed', 'Completed'
        FAILED = 'failed', 'Failed'
        REFUNDED = 'refunded', 'Refunded'
    
    class PaymentMethod(models.TextChoices):
        REMITA = 'remita', 'Remita'
        PAYSTACK = 'paystack', 'Paystack'
        FLUTTERWAVE = 'flutterwave', 'Flutterwave'
        BANK_TRANSFER = 'bank_transfer', 'Bank Transfer'
        USSD = 'ussd', 'USSD (*894#)'
        CASH = 'cash', 'Cash'
        POS = 'pos', 'POS'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='payments', null=True, blank=True)
    student = models.ForeignKey('students.Student', on_delete=models.CASCADE, related_name='payments')
    
    payment_reference = models.CharField(max_length=50, unique=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    payment_method = models.CharField(max_length=20, choices=PaymentMethod.choices)
    status = models.CharField(max_length=20, choices=PaymentStatus.choices, default=PaymentStatus.PENDING)
    
    # Payment gateway details
    gateway_reference = models.CharField(max_length=100, blank=True)  # From Remita, Paystack, etc.
    gateway_response = models.JSONField(null=True, blank=True)
    
    # For bank transfer
    bank_name = models.CharField(max_length=50, blank=True)
    transaction_date = models.DateTimeField(null=True, blank=True)
    
    # Nigerian specific
    remita_rrr = models.CharField(max_length=30, blank=True)  # Remita RRR
    paystack_ref = models.CharField(max_length=50, blank=True)
    
    # Confirmed by
    confirmed_by = models.ForeignKey('students.User', null=True, blank=True, on_delete=models.SET_NULL)
    confirmed_at = models.DateTimeField(null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'payments'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.payment_reference} - {self.amount}"


class Installment(models.Model):
    """Payment installments"""
    
    class InstallmentStatus(models.TextChoices):
        PENDING = 'pending', 'Pending'
        PAID = 'paid', 'Paid'
        OVERDUE = 'overdue', 'Overdue'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    student = models.ForeignKey('students.Student', on_delete=models.CASCADE, related_name='installments')
    semester = models.ForeignKey('university.Semester', on_delete=models.CASCADE, related_name='installments')
    
    installment_number = models.IntegerField()
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    due_date = models.DateField()
    paid_date = models.DateField(null=True, blank=True)
    
    status = models.CharField(max_length=20, choices=InstallmentStatus.choices, default=InstallmentStatus.PENDING)
    
    # Payment reference
    payment = models.ForeignKey(Payment, null=True, blank=True, on_delete=models.SET_NULL)
    
    class Meta:
        db_table = 'installments'
        unique_together = ['student', 'semester', 'installment_number']


class Scholarship(models.Model):
    """Scholarships and financial aid"""
    
    class ScholarshipType(models.TextChoices):
        TETFUND = 'tetfund', 'TETFund'
        FEDERAL = 'federal', 'Federal Government'
        STATE = 'state', 'State Government'
        INSTITUTIONAL = 'institutional', 'Institutional'
        EXTERNAL = 'external', 'External/Private'
    
    class ApplicationStatus(models.TextChoices):
        OPEN = 'open', 'Open'
        CLOSED = 'closed', 'Closed'
        REVIEW = 'review', 'Under Review'
        AWARDED = 'awarded', 'Awarded'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    university = models.ForeignKey('university.University', on_delete=models.CASCADE, related_name='scholarships')
    
    name = models.CharField(max_length=200)
    scholarship_type = models.CharField(max_length=20, choices=ScholarshipType.choices)
    
    description = models.TextField()
    
    # Amount
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    number_of_awards = models.IntegerField()
    
    # Eligibility
    eligible_levels = models.JSONField(default=list)
    eligible_programmes = models.JSONField(default=list)
    min_cgpa = models.FloatField(default=0)
    
    # Application
    application_start = models.DateField()
    application_end = models.DateField()
    status = models.CharField(max_length=20, choices=ApplicationStatus.choices, default=ApplicationStatus.OPEN)
    
    # Provider details
    provider_name = models.CharField(max_length=100, blank=True)
    provider_contact = models.CharField(max_length=100, blank=True)
    
    is_active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'scholarships'
        ordering = ['-application_end']


class ScholarshipApplication(models.Model):
    """Student scholarship applications"""
    
    class ApplicationStatus(models.TextChoices):
        PENDING = 'pending', 'Pending'
        SCREENING = 'screening', 'Screening'
        SHORTLISTED = 'shortlisted', 'Shortlisted'
        APPROVED = 'approved', 'Approved'
        REJECTED = 'rejected', 'Rejected'
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    student = models.ForeignKey('students.Student', on_delete=models.CASCADE, related_name='scholarship_applications')
    scholarship = models.ForeignKey(Scholarship, on_delete=models.CASCADE, related_name='applications')
    
    status = models.CharField(max_length=20, choices=ApplicationStatus.choices, default=ApplicationStatus.PENDING)
    
    # Documents
    supporting_documents = models.FileField(upload_to='scholarship_docs/', null=True, blank=True)
    
    # Decision
    amount_awarded = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    approved_by = models.ForeignKey('students.User', null=True, blank=True, on_delete=models.SET_NULL)
    approved_at = models.DateTimeField(null=True, blank=True)
    
    notes = models.TextField(blank=True)
    
    applied_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'scholarship_applications'
        unique_together = ['student', 'scholarship']


class TETFundRecord(models.Model):
    """TETFund levy and allocation tracking"""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    university = models.ForeignKey('university.University', on_delete=models.CASCADE, related_name='tetfund_records')
    student = models.ForeignKey('students.Student', on_delete=models.CASCADE, related_name='tetfund_records')
    semester = models.ForeignKey('university.Semester', on_delete=models.CASCADE, related_name='tetfund_records')
    
    # TETFund levy (2% of tuition)
    tuition_amount = models.DecimalField(max_digits=12, decimal_places=2)
    levy_amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    # Status
    remitted = models.BooleanField(default=False)
    remitted_date = models.DateField(null=True, blank=True)
    receipt_number = models.CharField(max_length=50, blank=True)
    
    # Allocation (for TETFund intervention)
    allocation_amount = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    allocation_used = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    
    year = models.IntegerField()
    
    class Meta:
        db_table = 'tetfund_records'
        unique_together = ['student', 'semester']