# Generated by Django 6.0.4 on 2026-04-21 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('marking_error', 'Marking Error'), ('grading_guidelines', 'Grading Guidelines Not Followed'), ('calculation_error', 'Calculation Error'), ('missing_work', 'Missing Work Not Considered'), ('examination_conditions', 'Examination Conditions'), ('medical_ground', 'Medical Grounds'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('expected_grade', models.CharField(max_length=5)),
                ('actual_grade', models.CharField(max_length=5)),
                ('evidence_files', models.JSONField(default=list)),
                ('supporting_documents', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('additional_info', 'Additional Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Senate')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_grade', models.CharField(blank=True, max_length=5)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appeals', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to='academic.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to='academic.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to='students.student')),
            ],
            options={
                'db_table': 'grade_appeals_new',
                'ordering': ['-created_at'],
                'unique_together': {('enrollment', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AppealTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='appeals.gradeappeal')),
            ],
            options={
                'db_table': 'appeal_timeline',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='appeals.gradeappeal')),
            ],
            options={
                'db_table': 'appeal_evidence',
            },
        ),
        migrations.CreateModel(
            name='AppealComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_comments', to=settings.AUTH_USER_MODEL)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appeals.gradeappeal')),
            ],
            options={
                'db_table': 'appeal_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeReviewCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField(default=list)),
                ('academic_session', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_committees', to='university.university')),
            ],
            options={
                'db_table': 'grade_review_committees',
                'unique_together': {('university', 'academic_session')},
            },
        ),
    ]
