# Generated by Django 6.0.4 on 2026-04-19 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('jamb_registration_number', models.CharField(blank=True, max_length=20)),
                ('caps_id', models.CharField(blank=True, max_length=50)),
                ('biometric_id', models.CharField(blank=True, max_length=100)),
                ('biometric_data', models.JSONField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('jamb_registration_number', models.CharField(blank=True, max_length=20)),
                ('jamb_score', models.IntegerField(blank=True, null=True)),
                ('post_utme_score', models.IntegerField(blank=True, null=True)),
                ('admission_method', models.CharField(blank=True, max_length=50)),
                ('matriculation_number', models.CharField(blank=True, max_length=30)),
                ('matriculation_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('admitted', 'Admitted'), ('matriculated', 'Matriculated'), ('active', 'Active'), ('graduating', 'Graduating'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='prospective', max_length=20)),
                ('student_type', models.CharField(blank=True, max_length=20)),
                ('gpa_scale', models.FloatField(default=4.0)),
                ('total_credits', models.IntegerField(default=0)),
                ('majors', models.JSONField(default=list)),
                ('minors', models.JSONField(default=list)),
                ('siwes_completed', models.BooleanField(default=False)),
                ('siwes_year', models.IntegerField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('departmental_clearance', models.BooleanField(default=False)),
                ('library_clearance', models.BooleanField(default=False)),
                ('hostel_clearance', models.BooleanField(default=False)),
                ('finance_clearance', models.BooleanField(default=False)),
                ('medical_clearance', models.BooleanField(default=False)),
                ('final_clearance', models.BooleanField(default=False)),
                ('on_probation', models.BooleanField(default=False)),
                ('probation_reason', models.TextField(blank=True)),
                ('outstanding_deficits', models.IntegerField(default=0)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hostel_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.hostel')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.programme')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-admitted_at'],
                'unique_together': {('university', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('admission_letter', 'Admission Letter'), ('jamb_admission', 'JAMB Admission'), ('o_level_result', 'O-Level Result'), ('a_level_result', 'A-Level Result'), ('birth_certificate', 'Birth Certificate'), ('id_card', 'ID Card'), ('medical_report', 'Medical Report'), ('siwes_certificate', 'SIWES Certificate'), ('transcript', 'Transcript')], max_length=30)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student')),
            ],
            options={
                'db_table': 'student_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
